git_auth_key: Your Git Authentication Key
User-Agent: MyClient/1.0.0
Accept: application/vnd.travis-ci.2+json
Host: api.travis-ci.org
Authorization: token Your Travis CI token
Content-Type: application/json
uri: https://api.travis-ci.org
